export const ExerciseDefinition: {
    [key: string]: string[]
} = {
    CHEST: [
        'Supino reto com barra',
        'Supino inclinado com barra',
        'Supino declinado com barra',
        'Supino reto com halteres',
        'Supino inclinado com halteres',
        'Supino declinado com halteres',
        'Crucifixo reto com halteres',
        'Crucifixo inclinado com halteres',
        'Crucifixo declinado com halteres',
        'Crucifixo em máquina',
        'Cross over',
        'Peck deck (voador)',
        'Flexão de braços (push-up)',
        'Flexão de braços com pegada fechada',
        'Flexão de braços com pegada larga',
        'Flexão de braços inclinada',
        'Flexão de braços declinada',
        'Supino com pegada neutra com halteres',
        'Supino com pegada invertida com barra',
        'Pull-over com halteres',
        'Pull-over em máquina',
        'Chest press em máquina',
        'Chest press inclinado em máquina',
        'Chest press declinado em máquina',
        'Smith machine bench press (supino no Smith)',
        'Cable fly (crucifixo na polia)',
        'Chest dips (mergulho para peito)',
        'Floor press com barra',
        'Floor press com halteres',
        'Fly em banco inclinado com halteres',
    ],
    BACK: [
        'Puxada frontal',
        'Puxada na polia alta com pegada aberta',
        'Puxada na polia alta com pegada fechada',
        'Remada curvada com barra',
        'Remada curvada com halteres',
        'Remada unilateral com halteres',
        'Remada na polia baixa',
        'Remada máquina Hammer',
        'Levantamento terra',
        'Levantamento terra romeno',
        'Pull-over na polia alta',
        'Puxada no graviton',
        'Remada cavalinho (T-bar row)',
        'Encolhimento de ombros com barra',
        'Encolhimento de ombros com halteres',
        'Remada invertida',
        'Remada alta com barra',
        'Good morning',
        'Superman',
        'Remada sentada na máquina',
        'Pullover com halteres',
        'Puxada no triângulo',
        'Puxada com pegada neutra',
        'Remada em pé com halteres',
        'Remada em pé com barra',
        'Levantamento terra com pegada snatch',
        'Puxada no puxador gironda',
        'Pull-up (barra fixa)',
        'Chin-up (barra fixa com pegada supinada)',
        'Remada com kettlebell',
    ],
    BICEPS: [
        'Rosca direta com barra',
        'Rosca direta com halteres',
        'Rosca alternada com halteres',
        'Rosca concentrada',
        'Rosca martelo',
        'Rosca Scott com barra',
        'Rosca Scott com halteres',
        'Rosca no banco inclinado com halteres',
        'Rosca 21',
        'Rosca na polia baixa',
        'Rosca na polia alta',
        'Rosca no cabo com pegada inversa',
        'Rosca no cabo com corda',
        'Rosca no cabo com barra',
        'Rosca de punho (wrist curl)',
        'Rosca inversa (reverse curl)',
        'Rosca no Smith',
        'Rosca com kettlebell',
        'Rosca concentrada em máquina',
        'Rosca em máquina',
        'Flexão de bíceps em suspensão (TRX)',
        'Flexão de bíceps com pegada supinada',
        'Rosca de punho inversa (reverse wrist curl)',
        'Rosca de punho com halteres',
        'Rosca de punho com barra',
        'Rosca Spider',
        'Rosca Zottman',
        'Rosca no banco preacher',
        'Chin-up (barra fixa com pegada supinada)',
        'Rosca de punho no cabo',
    ],
    TRICEPS: [
        'Tríceps no pulley',
        'Tríceps francês com halteres',
        'Tríceps francês com barra',
        'Tríceps francês unilateral',
        'Tríceps testa com barra',
        'Tríceps testa com halteres',
        'Tríceps mergulho em banco (bench dips)',
        'Tríceps coice (kickback) com halteres',
        'Tríceps coice (kickback) no cabo',
        'Tríceps no pulley com corda',
        'Tríceps no pulley com barra reta',
        'Tríceps no pulley com barra W',
        'Tríceps no pulley com pegada inversa',
        'Tríceps na máquina',
        'Tríceps na polia alta',
        'Tríceps na polia baixa',
        'Tríceps no banco inclinado com halteres',
        'Tríceps no banco declinado com halteres',
        'Tríceps mergulho em paralelas (parallel bar dips)',
        'Extensão de tríceps com kettlebell',
        'Tríceps com elástico',
        'Tríceps com pegada diamante (diamond push-up)',
        'Tríceps no Smith',
        'Tríceps no banco Scott com barra',
        'Tríceps no banco Scott com halteres',
        'Tríceps francês no cabo',
        'Tríceps na barra fixa com pegada supinada',
        'Tríceps com pegada neutra no banco inclinado',
        'Tríceps com pegada fechada no supino',
        'Tríceps coice (kickback) com kettlebell',
    ],
    SHOULDERS: [
        'Desenvolvimento com barra',
        'Desenvolvimento com halteres',
        'Desenvolvimento Arnold',
        'Elevação lateral com halteres',
        'Elevação frontal com halteres',
        'Elevação lateral na polia',
        'Elevação frontal na polia',
        'Elevação lateral inclinada',
        'Elevação frontal com barra',
        'Desenvolvimento na máquina',
        'Remada alta com barra',
        'Remada alta com halteres',
        'Crucifixo inverso com halteres',
        'Crucifixo inverso na máquina',
        'Elevação posterior com halteres',
        'Elevação posterior na polia',
        'Face pull',
        'Encostada na parede (wall press)',
        'Desenvolvimento militar',
        'Desenvolvimento com pegada neutra',
        'Pressão de ombros no Smith',
        'Pressão de ombros com kettlebell',
        'Elevação lateral com kettlebell',
        'Elevação frontal com kettlebell',
        'Desenvolvimento com elástico',
        'Elevação lateral com elástico',
        'Elevação frontal com elástico',
        'Elevação lateral no banco inclinado',
        'Elevação frontal no banco inclinado',
        'Desenvolvimento com pegada pronada',
    ],
    LEGS: [
        'Agachamento com barra',
        'Agachamento frontal com barra',
        'Agachamento sumô com barra',
        'Agachamento com halteres',
        'Leg press',
        'Hack squat',
        'Extensão de perna na máquina',
        'Flexão de perna na máquina',
        'Stiff com barra',
        'Stiff com halteres',
        'Levantamento terra romeno',
        'Avanço com halteres',
        'Afundo com barra',
        'Afundo búlgaro',
        'Cadeira adutora',
        'Cadeira abdutora',
        'Ponte de glúteos',
        'Levantamento de panturrilha em pé',
        'Levantamento de panturrilha sentado',
        'Levantamento de panturrilha no leg press',
        'Agachamento sumô com kettlebell',
        'Levantamento terra sumô',
        'Good morning',
        'Agachamento no Smith',
        'Leg press horizontal',
        'Leg press 45 graus',
        'Extensão de quadril na máquina',
        'Glúteo na polia',
        'Agachamento no hack',
        'Agachamento livre',
    ],
    ABS: [
        'Abdominal crunch',
        'Abdominal crunch na máquina',
        'Abdominal oblíquo',
        'Abdominal infra com elevação de pernas',
        'Abdominal infra na barra',
        'Prancha',
        'Prancha lateral',
        'Elevação de pernas',
        'Abdominal com corda na polia',
        'Abdominal bicicleta',
        'Abdominal reverso',
        'Abdominal V-up',
        'Abdominal no rolo',
        'Abdominal com anilha',
        'Abdominal na bola suíça',
        'Abdominal canivete',
        'Prancha com elevação de perna',
        'Abdominal escalador (mountain climber)',
        'Abdominal com roda de exercício',
        'Abdominal com kettlebell',
        'Abdominal oblíquo com halteres',
        'Abdominal com bola medicinal',
        'Abdominal na barra paralela',
        'Prancha com movimento lateral',
        'Abdominal no banco declinado',
        'Abdominal com pernas suspensas',
        'Abdominal com torção',
        'Prancha dinâmica',
        'Prancha com elevação de braço',
        'Abdominal hollow hold',
    ],
    GLUTES: [
        'Agachamento com barra',
        'Agachamento sumô com halteres',
        'Elevação de quadril (hip thrust) com barra',
        'Elevação de quadril (hip thrust) com halteres',
        'Afundo com halteres',
        'Afundo búlgaro',
        'Agachamento com kettlebell',
        'Ponte de glúteos',
        'Ponte de glúteos com uma perna',
        'Step-up com halteres',
        'Leg press',
        'Levantamento terra romeno',
        'Levantamento terra sumô',
        'Extensão de quadril na máquina',
        'Glúteo na polia baixa',
        'Abdução de quadril na máquina',
        'Agachamento no Smith',
        'Glúteo 4 apoios',
        'Agachamento no hack',
        'Agachamento frontal com barra',
        'Good morning',
        'Cadeira abdutora',
        'Extensão de quadril na bola suíça',
        'Glúteo na polia com perna estendida',
        'Glúteo no banco com perna estendida',
        'Kickback com elástico',
        'Step-up no banco',
        'Agachamento com salto',
        'Agachamento pistola',
        'Elevação de quadril na bola suíça',
    ],
}
